### ISSUE TITLE
testt

### ISSUE THREAD

**Issue by peteryang1756** [thomasbnt/hello-to-news-contributions#1]
test

**Comment by thomasbnt** [comment]
Hello @ssangyongsports  ! It didn't work because when I created this workflow in 2020, I think the `description` should be in `workflow/action.yml`.

You can see the recent change for the Action works correctly : https://github.com/thomasbnt/hello-to-news-contributions/commit/4c707faff361c59002630dbc25c3ea10df29ca4e
